// Code generated by protoc-gen-go. DO NOT EDIT.
// source: server.proto

package proto

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// The request message containing contacts data
type Contact struct {
	Id                   int64    `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Phone                string   `protobuf:"bytes,2,opt,name=phone,proto3" json:"phone,omitempty"`
	FirstName            string   `protobuf:"bytes,3,opt,name=first_name,json=firstName,proto3" json:"first_name,omitempty"`
	LastName             string   `protobuf:"bytes,4,opt,name=last_name,json=lastName,proto3" json:"last_name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Contact) Reset()         { *m = Contact{} }
func (m *Contact) String() string { return proto.CompactTextString(m) }
func (*Contact) ProtoMessage()    {}
func (*Contact) Descriptor() ([]byte, []int) {
	return fileDescriptor_ad098daeda4239f7, []int{0}
}

func (m *Contact) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Contact.Unmarshal(m, b)
}
func (m *Contact) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Contact.Marshal(b, m, deterministic)
}
func (m *Contact) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Contact.Merge(m, src)
}
func (m *Contact) XXX_Size() int {
	return xxx_messageInfo_Contact.Size(m)
}
func (m *Contact) XXX_DiscardUnknown() {
	xxx_messageInfo_Contact.DiscardUnknown(m)
}

var xxx_messageInfo_Contact proto.InternalMessageInfo

func (m *Contact) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *Contact) GetPhone() string {
	if m != nil {
		return m.Phone
	}
	return ""
}

func (m *Contact) GetFirstName() string {
	if m != nil {
		return m.FirstName
	}
	return ""
}

func (m *Contact) GetLastName() string {
	if m != nil {
		return m.LastName
	}
	return ""
}

type ID struct {
	Id                   int64    `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ID) Reset()         { *m = ID{} }
func (m *ID) String() string { return proto.CompactTextString(m) }
func (*ID) ProtoMessage()    {}
func (*ID) Descriptor() ([]byte, []int) {
	return fileDescriptor_ad098daeda4239f7, []int{1}
}

func (m *ID) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ID.Unmarshal(m, b)
}
func (m *ID) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ID.Marshal(b, m, deterministic)
}
func (m *ID) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ID.Merge(m, src)
}
func (m *ID) XXX_Size() int {
	return xxx_messageInfo_ID.Size(m)
}
func (m *ID) XXX_DiscardUnknown() {
	xxx_messageInfo_ID.DiscardUnknown(m)
}

var xxx_messageInfo_ID proto.InternalMessageInfo

func (m *ID) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

type Phone struct {
	Phone                string   `protobuf:"bytes,1,opt,name=phone,proto3" json:"phone,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Phone) Reset()         { *m = Phone{} }
func (m *Phone) String() string { return proto.CompactTextString(m) }
func (*Phone) ProtoMessage()    {}
func (*Phone) Descriptor() ([]byte, []int) {
	return fileDescriptor_ad098daeda4239f7, []int{2}
}

func (m *Phone) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Phone.Unmarshal(m, b)
}
func (m *Phone) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Phone.Marshal(b, m, deterministic)
}
func (m *Phone) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Phone.Merge(m, src)
}
func (m *Phone) XXX_Size() int {
	return xxx_messageInfo_Phone.Size(m)
}
func (m *Phone) XXX_DiscardUnknown() {
	xxx_messageInfo_Phone.DiscardUnknown(m)
}

var xxx_messageInfo_Phone proto.InternalMessageInfo

func (m *Phone) GetPhone() string {
	if m != nil {
		return m.Phone
	}
	return ""
}

type ListReply struct {
	People               []*Contact `protobuf:"bytes,1,rep,name=people,proto3" json:"people,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *ListReply) Reset()         { *m = ListReply{} }
func (m *ListReply) String() string { return proto.CompactTextString(m) }
func (*ListReply) ProtoMessage()    {}
func (*ListReply) Descriptor() ([]byte, []int) {
	return fileDescriptor_ad098daeda4239f7, []int{3}
}

func (m *ListReply) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListReply.Unmarshal(m, b)
}
func (m *ListReply) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListReply.Marshal(b, m, deterministic)
}
func (m *ListReply) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListReply.Merge(m, src)
}
func (m *ListReply) XXX_Size() int {
	return xxx_messageInfo_ListReply.Size(m)
}
func (m *ListReply) XXX_DiscardUnknown() {
	xxx_messageInfo_ListReply.DiscardUnknown(m)
}

var xxx_messageInfo_ListReply proto.InternalMessageInfo

func (m *ListReply) GetPeople() []*Contact {
	if m != nil {
		return m.People
	}
	return nil
}

// The response message on save actiob
type SaveReply struct {
	Id                   int64    `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SaveReply) Reset()         { *m = SaveReply{} }
func (m *SaveReply) String() string { return proto.CompactTextString(m) }
func (*SaveReply) ProtoMessage()    {}
func (*SaveReply) Descriptor() ([]byte, []int) {
	return fileDescriptor_ad098daeda4239f7, []int{4}
}

func (m *SaveReply) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SaveReply.Unmarshal(m, b)
}
func (m *SaveReply) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SaveReply.Marshal(b, m, deterministic)
}
func (m *SaveReply) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SaveReply.Merge(m, src)
}
func (m *SaveReply) XXX_Size() int {
	return xxx_messageInfo_SaveReply.Size(m)
}
func (m *SaveReply) XXX_DiscardUnknown() {
	xxx_messageInfo_SaveReply.DiscardUnknown(m)
}

var xxx_messageInfo_SaveReply proto.InternalMessageInfo

func (m *SaveReply) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

type LoadReply struct {
	People               *Contact `protobuf:"bytes,1,opt,name=people,proto3" json:"people,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *LoadReply) Reset()         { *m = LoadReply{} }
func (m *LoadReply) String() string { return proto.CompactTextString(m) }
func (*LoadReply) ProtoMessage()    {}
func (*LoadReply) Descriptor() ([]byte, []int) {
	return fileDescriptor_ad098daeda4239f7, []int{5}
}

func (m *LoadReply) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LoadReply.Unmarshal(m, b)
}
func (m *LoadReply) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LoadReply.Marshal(b, m, deterministic)
}
func (m *LoadReply) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LoadReply.Merge(m, src)
}
func (m *LoadReply) XXX_Size() int {
	return xxx_messageInfo_LoadReply.Size(m)
}
func (m *LoadReply) XXX_DiscardUnknown() {
	xxx_messageInfo_LoadReply.DiscardUnknown(m)
}

var xxx_messageInfo_LoadReply proto.InternalMessageInfo

func (m *LoadReply) GetPeople() *Contact {
	if m != nil {
		return m.People
	}
	return nil
}

type DeleteReply struct {
	Status               string   `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeleteReply) Reset()         { *m = DeleteReply{} }
func (m *DeleteReply) String() string { return proto.CompactTextString(m) }
func (*DeleteReply) ProtoMessage()    {}
func (*DeleteReply) Descriptor() ([]byte, []int) {
	return fileDescriptor_ad098daeda4239f7, []int{6}
}

func (m *DeleteReply) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeleteReply.Unmarshal(m, b)
}
func (m *DeleteReply) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeleteReply.Marshal(b, m, deterministic)
}
func (m *DeleteReply) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeleteReply.Merge(m, src)
}
func (m *DeleteReply) XXX_Size() int {
	return xxx_messageInfo_DeleteReply.Size(m)
}
func (m *DeleteReply) XXX_DiscardUnknown() {
	xxx_messageInfo_DeleteReply.DiscardUnknown(m)
}

var xxx_messageInfo_DeleteReply proto.InternalMessageInfo

func (m *DeleteReply) GetStatus() string {
	if m != nil {
		return m.Status
	}
	return ""
}

func init() {
	proto.RegisterType((*Contact)(nil), "Contact")
	proto.RegisterType((*ID)(nil), "ID")
	proto.RegisterType((*Phone)(nil), "Phone")
	proto.RegisterType((*ListReply)(nil), "ListReply")
	proto.RegisterType((*SaveReply)(nil), "SaveReply")
	proto.RegisterType((*LoadReply)(nil), "LoadReply")
	proto.RegisterType((*DeleteReply)(nil), "DeleteReply")
}

func init() { proto.RegisterFile("server.proto", fileDescriptor_ad098daeda4239f7) }

var fileDescriptor_ad098daeda4239f7 = []byte{
	// 297 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x6c, 0x91, 0xd1, 0x4a, 0xc3, 0x30,
	0x14, 0x86, 0x9b, 0xb6, 0xab, 0xeb, 0xe9, 0xf0, 0xe2, 0x30, 0xa4, 0x6e, 0x54, 0x4a, 0x44, 0xe8,
	0x8d, 0xb9, 0x98, 0x6f, 0x30, 0x7b, 0x33, 0x10, 0x91, 0xfa, 0x00, 0x12, 0x6d, 0xc4, 0xb2, 0xae,
	0x29, 0x6d, 0x1c, 0xec, 0x1d, 0x7c, 0x68, 0x49, 0x9a, 0x95, 0x31, 0xbd, 0x0a, 0xe7, 0xfc, 0x27,
	0xff, 0xff, 0xe5, 0x04, 0x66, 0xbd, 0xe8, 0xf6, 0xa2, 0x63, 0x6d, 0x27, 0x95, 0xa4, 0x5b, 0xb8,
	0x78, 0x94, 0x8d, 0xe2, 0x1f, 0x0a, 0x2f, 0xc1, 0xad, 0xca, 0x98, 0xa4, 0x24, 0xf3, 0x0a, 0xb7,
	0x2a, 0x71, 0x0e, 0x93, 0xf6, 0x4b, 0x36, 0x22, 0x76, 0x53, 0x92, 0x85, 0xc5, 0x50, 0x60, 0x02,
	0xf0, 0x59, 0x75, 0xbd, 0x7a, 0x6b, 0xf8, 0x4e, 0xc4, 0x9e, 0x91, 0x42, 0xd3, 0x79, 0xe6, 0x3b,
	0x81, 0x4b, 0x08, 0x6b, 0x7e, 0x54, 0x7d, 0xa3, 0x4e, 0x75, 0x43, 0x8b, 0x74, 0x0e, 0xee, 0x26,
	0x3f, 0xcf, 0xa1, 0x09, 0x4c, 0x5e, 0x8c, 0xf5, 0x18, 0x48, 0x4e, 0x02, 0xe9, 0x3d, 0x84, 0x4f,
	0x55, 0xaf, 0x0a, 0xd1, 0xd6, 0x07, 0x4c, 0x21, 0x68, 0x85, 0x6c, 0x6b, 0x3d, 0xe3, 0x65, 0xd1,
	0x6a, 0xca, 0x2c, 0x7d, 0x61, 0xfb, 0x74, 0x09, 0xe1, 0x2b, 0xdf, 0x8b, 0x61, 0xfc, 0x3c, 0x4a,
	0x7b, 0x49, 0x5e, 0xfe, 0xf5, 0x22, 0xff, 0x7a, 0xdd, 0x41, 0x94, 0x8b, 0x5a, 0x28, 0xeb, 0x76,
	0x05, 0x41, 0xaf, 0xb8, 0xfa, 0xee, 0x2d, 0xa0, 0xad, 0x56, 0x3f, 0x04, 0x22, 0x7b, 0x75, 0x2d,
	0xe5, 0x16, 0x6f, 0xc0, 0xd7, 0x08, 0x38, 0x1a, 0x2e, 0x80, 0x8d, 0x4c, 0xd4, 0xc1, 0x6b, 0xf0,
	0x35, 0x05, 0x7a, 0x6c, 0x93, 0x2f, 0x80, 0x8d, 0x44, 0xd4, 0xc1, 0x5b, 0x88, 0xf4, 0x63, 0xd7,
	0x87, 0x61, 0x23, 0x01, 0x33, 0xa7, 0x1e, 0x3a, 0xae, 0x80, 0x3a, 0x98, 0x40, 0x30, 0x60, 0x0d,
	0x0e, 0x33, 0x76, 0x02, 0x49, 0x9d, 0xf7, 0xc0, 0xfc, 0xec, 0xc3, 0x6f, 0x00, 0x00, 0x00, 0xff,
	0xff, 0x52, 0xde, 0xb0, 0x23, 0xe9, 0x01, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// ContactBookClient is the client API for ContactBook service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type ContactBookClient interface {
	Save(ctx context.Context, in *Contact, opts ...grpc.CallOption) (*SaveReply, error)
	Load(ctx context.Context, in *ID, opts ...grpc.CallOption) (*LoadReply, error)
	ListByPhone(ctx context.Context, in *Phone, opts ...grpc.CallOption) (*ListReply, error)
	Delete(ctx context.Context, in *ID, opts ...grpc.CallOption) (*DeleteReply, error)
}

type contactBookClient struct {
	cc *grpc.ClientConn
}

func NewContactBookClient(cc *grpc.ClientConn) ContactBookClient {
	return &contactBookClient{cc}
}

func (c *contactBookClient) Save(ctx context.Context, in *Contact, opts ...grpc.CallOption) (*SaveReply, error) {
	out := new(SaveReply)
	err := c.cc.Invoke(ctx, "/ContactBook/Save", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *contactBookClient) Load(ctx context.Context, in *ID, opts ...grpc.CallOption) (*LoadReply, error) {
	out := new(LoadReply)
	err := c.cc.Invoke(ctx, "/ContactBook/Load", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *contactBookClient) ListByPhone(ctx context.Context, in *Phone, opts ...grpc.CallOption) (*ListReply, error) {
	out := new(ListReply)
	err := c.cc.Invoke(ctx, "/ContactBook/ListByPhone", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *contactBookClient) Delete(ctx context.Context, in *ID, opts ...grpc.CallOption) (*DeleteReply, error) {
	out := new(DeleteReply)
	err := c.cc.Invoke(ctx, "/ContactBook/Delete", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ContactBookServer is the server API for ContactBook service.
type ContactBookServer interface {
	Save(context.Context, *Contact) (*SaveReply, error)
	Load(context.Context, *ID) (*LoadReply, error)
	ListByPhone(context.Context, *Phone) (*ListReply, error)
	Delete(context.Context, *ID) (*DeleteReply, error)
}

// UnimplementedContactBookServer can be embedded to have forward compatible implementations.
type UnimplementedContactBookServer struct {
}

func (*UnimplementedContactBookServer) Save(ctx context.Context, req *Contact) (*SaveReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Save not implemented")
}
func (*UnimplementedContactBookServer) Load(ctx context.Context, req *ID) (*LoadReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Load not implemented")
}
func (*UnimplementedContactBookServer) ListByPhone(ctx context.Context, req *Phone) (*ListReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListByPhone not implemented")
}
func (*UnimplementedContactBookServer) Delete(ctx context.Context, req *ID) (*DeleteReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Delete not implemented")
}

func RegisterContactBookServer(s *grpc.Server, srv ContactBookServer) {
	s.RegisterService(&_ContactBook_serviceDesc, srv)
}

func _ContactBook_Save_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Contact)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ContactBookServer).Save(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/ContactBook/Save",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ContactBookServer).Save(ctx, req.(*Contact))
	}
	return interceptor(ctx, in, info, handler)
}

func _ContactBook_Load_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ID)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ContactBookServer).Load(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/ContactBook/Load",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ContactBookServer).Load(ctx, req.(*ID))
	}
	return interceptor(ctx, in, info, handler)
}

func _ContactBook_ListByPhone_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Phone)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ContactBookServer).ListByPhone(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/ContactBook/ListByPhone",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ContactBookServer).ListByPhone(ctx, req.(*Phone))
	}
	return interceptor(ctx, in, info, handler)
}

func _ContactBook_Delete_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ID)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ContactBookServer).Delete(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/ContactBook/Delete",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ContactBookServer).Delete(ctx, req.(*ID))
	}
	return interceptor(ctx, in, info, handler)
}

var _ContactBook_serviceDesc = grpc.ServiceDesc{
	ServiceName: "ContactBook",
	HandlerType: (*ContactBookServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Save",
			Handler:    _ContactBook_Save_Handler,
		},
		{
			MethodName: "Load",
			Handler:    _ContactBook_Load_Handler,
		},
		{
			MethodName: "ListByPhone",
			Handler:    _ContactBook_ListByPhone_Handler,
		},
		{
			MethodName: "Delete",
			Handler:    _ContactBook_Delete_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "server.proto",
}
